title: Evolutionary Computation with Jupyter/IPython
description: Notebooks about genetic and evolutionary computation.
google_analytics:
show_downloads: true
theme: jekyll-theme-time-machine

gems:
  - jekyll-mentions
